sonar.projectKey=diazdesandi_org-iac
sonar.organization=diazdesandi

sonar.projectName=org-iac
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=test

sonar.javascript.lcov.reportPaths=coverage/lcov.info