owner: diazdesandi
organization: diazdesandi-org

defaults:
  visibility: public
  default_branch: main
  delete_branch_on_merge: true
  merge_strategies:
    - squash
  features:
    issues: true
    wiki: false
    projects: false
    discussions: false
