rulesets:
  - id: repo-main-default
    target: branch
    enforcement: active
    conditions:
      include:
        - "~DEFAULT_BRANCH"
    rules:
      required_linear_history: true
      deletion: false
      non_fast_forward: false
      pull_request:
        required_approving_review_count: 1
        dismiss_stale_reviews_on_push: true
        require_code_owner_review: false
      required_status_checks:
        strict: true
        checks:
          - context: build

  - id: release-branch-protection
    target: branch
    enforcement: active
    conditions:
      include:
        - "refs/heads/release/*"
    rules:
      required_linear_history: true
      deletion: false
      non_fast_forward: false
      pull_request:
        required_approving_review_count: 1
        dismiss_stale_reviews_on_push: true
        require_code_owner_review: false
