rulesets:
  - id: repo-main-default
    target: branch
    enforcement: active
    conditions:
      include:
        - "~DEFAULT_BRANCH"
    rules:
      requiredLinearHistory: true
      deletion: false
      nonFastForward: false
      pullRequest:
        requiredApprovingReviewCount: 1
        dismissStaleReviewsOnPush: true
        requireCodeOwnerReview: false
      requiredStatusChecks:
        strict: true
        checks:
          - context: build

  - id: release-branch-protection
    target: branch
    enforcement: active
    conditions:
      include:
        - "refs/heads/release/*"
    rules:
      requiredLinearHistory: true
      deletion: false
      nonFastForward: false
      pullRequest:
        requiredApprovingReviewCount: 1
        dismissStaleReviewsOnPush: true
        requireCodeOwnerReview: false
