rulesets:
  - id: repo-main-default
    target: branch
    enforcement: active
    conditions:
      refName:
        includes:
          - "~DEFAULT_BRANCH"
    rules:
      requiredLinearHistory: true
      deletion: false
      nonFastForward: false
      pullRequest:
        requiredApprovingReviewCount: 1
        dismissStaleReviewsOnPush: true
        requireCodeOwnerReview: false
      requiredStatusChecks:
        requiredChecks:
          - context: build
        strictRequiredStatusChecksPolicy: true

  - id: release-branch-protection
    target: branch
    enforcement: active
    conditions:
      refName:
        includes:
          - "refs/heads/release/*"
    rules:
      requiredLinearHistory: true
      deletion: false
      nonFastForward: false
      pullRequest:
        requiredApprovingReviewCount: 1
        dismissStaleReviewsOnPush: true
        requireCodeOwnerReview: false