name: Deploy
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/cd.yml"
      - ".github/workflows/pulumi.yml"
      - "src/**"
      - "config/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: pulumi-deploy
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/pulumi.yml
    secrets: inherit
    with:
      command: up
